language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: dhnSUtCl3rh5Xo6tvJKbL/XgJcmmULtzz2Jv9vK1IpR6tFagbWIQI7GABvj1FU91ya5PE/JjSvLFyrzxP9ja6fByvcgAYTXIB4wKcrAUIbPBLLDkO9wqZqV1qEst1ebQNFzxx2eCDSsh5GKzEf6v9/1986kgzJ/rXOQvmv5ARfhaZuaDhqV7XdNp5xq69i8pEsCqavmnbcr1h+OKz6tBy7CFljIGribA3Y2aQIvwo1nARnZWhoix098OMjHOnXT/yOBjLx5SAa0X2Fj8yFInmSFSptQtWkIaFag3Aakov6zh1p3Q07/RjCAOUZn/gJkxUgDHgrVTX/0NLkoptd7CgX8Qem1n3D6CQC9lqrqVfP6ps5ezRbp+P87CyGLIw3Onk+mRHPcTGiQTyPDXEYYPBwuI2tWIeAVUyle+sIAAp76/lgf2tIFlP8p341N3K7u39OX0hrSXtvgrgCeBTu7QT0mMCAmK3pCYskPaoLbRRQTHmXzxoyqSUlQ6qDpUEWIwyUsnY6JmNvTu0Atd7ScvvaJ0Db3r/p65e0oy3x7qJAcT33ddSAoAWdRbaLdK1gIJXEG6QVtZs3V6f8ut17xIoyYMiCCOxRXNlPS4vEz1A0ditscNRkxQBjBd0rqCH++fJP1eIS8dn3wC+z18wVic/TF7BPFCebKk/WipcvkJ3LE=
